version: "3.7"
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - local
  api:
    build: .
    entrypoint: "./docker/entrypoint.sh"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/app
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "6001:3000"
    networks:
      - local
      - webgateway
    labels:
      - traefik.http.routers.authapi.rule=Host(`school-api.slightlytechie.com`)
      - traefik.http.routers.authapi.tls=true
      - traefik.http.routers.authapi.tls.certresolver=lets-encrypt
      - traefik.port=6001

volumes:
  postgres_data: {}
  app-storage: {}

networks:
  local:
  webgateway:
    external: true