name: SSH Deploy

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SCHOOL_SSH_PRIVATE_KEY }}

      - name: SSH into the remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa ${{secrets.SCHOOL_SSH_USERNAME}}@${{secrets.SCHOOL_SSH_HOST}}
          cd /home/kwesi/apps/st-school-api
          git pull origin main
          docker-compose up --build -d
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SCHOOL_SSH_PRIVATE_KEY }}